---
- name: Configure IPoIB interfaces
  ansible.builtin.template:
    src: ifcfg-ib.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.iface }}
  loop: "{{ mlnx_ofed_ipoib_interfaces }}"
  loop_control:
    index_var: idx
    label: "Configure {{ item.iface }}"
  notify: Restart interface
  register: configure_ipoib
