---
- name: Configure IPoIB interfaces
  ansible.builtin.template:
    src: ifcfg-ib.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.iface }}
  loop: "{{ infiniband_ipoib_interfaces }}"
  loop_control:
    index_var: idx
    label: "Configure {{ item.iface }}"
  notify: Restart interface
  register: configure_ipoib

- name: Configure ipoib_enhanced
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/ib_ipoib_enhanced.conf
    line: "options ib_ipoib ipoib_enhanced={{ infiniband_ipoib_enhanced | bool | int }}"
    create: true
  notify: Restart openibd
