---
- name: Configure IPoIB interfaces
  ansible.builtin.template:
    src: ib.cfg.j2
    dest: /etc/network/interfaces.d/{{ item.iface }}.cfg
  loop: "{{ mlnx_ofed_ipoib_interfaces }}"
  loop_control:
    index_var: idx
    label: "Configure {{ item.iface }}"
  notify: Restart interface
  register: configure_ipoib
