---
- name: Source configuration files of IPoIB interfaces
  ansible.builtin.lineinfile:
    path: /etc/network/interfaces
    line: source /etc/network/interfaces.d/{{ item.iface }}.cfg
    insertbefore: BOF
  loop: "{{ mlnx_ofed_ipoib_interfaces | sort(reverse=True, attribute='iface') }}"
  loop_control:
    index_var: idx
    label: "Source interface file for {{ item.iface }}"

- name: Configure IPoIB interfaces
  ansible.builtin.template:
    src: ib.cfg.j2
    dest: /etc/network/interfaces.d/{{ item.iface }}.cfg
  loop: "{{ mlnx_ofed_ipoib_interfaces }}"
  loop_control:
    index_var: idx
    label: "Configure {{ item.iface }}"
  notify: Restart interface
  register: configure_ipoib
