---
- name: Install OFED packages
  ansible.builtin.package:
    name:
      - "{{ infiniband_ofed_package }}"
    state: "{{ 'latest' if infiniband_upgrade else 'present' }}"
  notify: "Ensure openibd.service is started"
