---
- name: Install MLNX_OFED packages
  ansible.builtin.package:
    name:
      - "mlnx-ofed-{{ infiniband_mlnx_ofed_flavor }}"
    state: "{{ 'latest' if infiniband_upgrade else 'present' }}"
  notify: "Ensure openibd.service is started"
