---
- name: Install MLNX_OFED kernel packages for Debian OS family
  ansible.builtin.package:
    name:
      - mlnx-ofed-kernel-dkms
      - mlnx-ofed-kernel-utils
      - "{{ infiniband_kernel_headers_package }}-{{ ansible_facts['kernel'] }}"
    state: "{{ 'latest' if infiniband_upgrade else 'present' }}"
  register: packages_install
  notify: "Ensure openibd.service is started"

- name: Build and install the modules with DKMS
  ansible.builtin.command: dkms autoinstall  # noqa 503 no-handler
  when: packages_install.changed
