---
- name: Install MLNX_OFED packages for Red Hat OS family
  ansible.builtin.package:
    name:
      - mlnx-ofa_kernel-devel
      - kmod-mlnx-ofa_kernel
  notify: "Ensure openibd.service is started"
