---
- name: Configure repositories
  ansible.builtin.include_tasks:
    file: "repositories-{{ ansible_facts['os_family'] }}.yml"
  when: mlnx_ofed_configure_repos

- name: Install MLNX_OFED kernel modules
  ansible.builtin.include_tasks:
    file: "install-{{ ansible_facts['os_family'] }}.yml"
  when: mlnx_ofed_install_kernel_modules

- name: Install common MLNX_OFED packages
  ansible.builtin.package:
    name:
      - infiniband-diags

- name: Flush handlers
  meta: flush_handlers

- name: Configure IPoIB interfaces
  ansible.builtin.include_tasks:
    file: "configure-{{ ansible_facts['os_family'] }}.yml"
