---
- name: Configure repositories
  ansible.builtin.include_tasks:
    file: "repositories-{{ ansible_facts['os_family'] }}.yml"
  when: infiniband_configure_repos

- name: Install MLNX_OFED kernel modules
  ansible.builtin.include_tasks:
    file: "install-{{ ansible_facts['os_family'] }}.yml"
  when: infiniband_install_kernel_modules

- name: Install common InfiniBand packages
  ansible.builtin.package:
    name:
      - infiniband-diags
      - mstflint
      - perftest

- name: Configure Mellanox HCAs
  ansible.builtin.include_tasks:
    file: "configure_hca-{{ ansible_facts['os_family'] }}.yml"
  when: infiniband_hca_devices is defined

- name: Flush handlers
  meta: flush_handlers

  # Include only when at least one item has 'sriov_en: True'
- name: Configure SR-IOV
  ansible.builtin.include_tasks:
    file: "configure_sriov-{{ ansible_facts['os_family'] }}.yml"
  when: infiniband_hca_devices is defined and
    (infiniband_hca_devices | map(attribute='sriov_en') | list) is any

- name: Configure IPoIB interfaces
  ansible.builtin.include_tasks:
    file: "configure-{{ ansible_facts['os_family'] }}.yml"
  when: infiniband_ipoib_interfaces is defined
