---
- name: Install GPG-KEY
  ansible.builtin.apt_key:
    url: "{{ infiniband_gpg_key }}"
    keyring: /etc/apt/trusted.gpg.d/infiniband.gpg

- name: Configure InfiniBand repository
  ansible.builtin.copy:
    content: "{{ infiniband_apt_repository }}\n"
    dest: /etc/apt/sources.list.d/infiniband.list
    mode: 0644

- name: "Update repository cache"
  apt:
    update_cache: yes
