---
- name: Install GPG-KEY
  ansible.builtin.rpm_key:
    key: "{{ infiniband_gpg_key }}"
    state: present

- name: Configure InfiniBand repository
  ansible.builtin.yum_repository:
    name: infiniband
    baseurl: "{{ infiniband_yum_repository }}"
    description: "InfiniBand repository"
    enabled: True
    gpgcheck: True
    gpgkey: "{{ infiniband_gpg_key }}"
