---
- name: Restart interface
  command: bash -c "ifdown {{ item.item.iface }} && ifup {{ item.item.iface }}"
  loop: "{{ configure_ipoib.results }}"
  loop_control:
    label: "Restart interface {{ item.item.iface }}"
  when: item.changed

- name: Ensure openibd.service is started
  ansible.builtin.systemd:
    name: openibd.service
    state: started

- name: Restart openibd
  ansible.builtin.systemd:
    name: openibd.service
    state: restarted

- name: Reboot to load new configurations
  throttle: "{{ infiniband_throttle_reboot }}"
  ansible.builtin.reboot:
    msg: "Infiniband: Reboot machine to load new configurations."
  when: infiniband_allow_reboot

- name: Restart sysfsutils
  ansible.builtin.systemd:
    name: sysfsutils.service
    state: restarted
