---
- name: Restart interface
  command: bash -c "ifdown {{ item.item.iface }} && ifup {{ item.item.iface }}"
  loop: "{{ configure_ipoib.results }}"
  loop_control:
    label: "Restart interface {{ item.item.iface }}"
  when: item.changed

- name: Ensure openibd.service is started
  ansible.builtin.systemd:
    name: openibd.service
    state: started
